### ISSUE TITLE
Tracklet Crashing System

### ISSUE THREAD

**Issue by dmccarthy-dev** [OPENi-ict/tracklet#2]
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:35:20
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:544:30
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:141:23
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:254:17
    at done (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:129:15)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:32:16
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:251:21
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/async/lib/async.js:575:34
    at Request._callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:302:17)
    at self.callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/request/request.js:360:22)

**Comment by philipobrien** [comment]
What were you doing when this happened, so I can try reproduce it?

**Comment by dmccarthy-dev** [comment]
Its crashing demo2 again. I wasn't using the site so I cannot give any more information. Stacktrace.....

[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at Quit._callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:39:26)
    at Quit.Sequence.end (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol._validateEnqueue (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:218:6)
    at Protocol._enqueue (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Protocol.quit (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/protocol/Protocol.js:87:36)
    at Connection.end (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/mysql/lib/Connection.js:215:18)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:37:24
    at Request._callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/lib/main.js:208:17)
    at Request.self.callback (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/tracklet/node_modules/request/request.js:360:22)
    at Request.emit (events.js:98:17)
